apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config-skf-flask
data:
  ORIGIN: skf-flask-back
  JWT_SECRET: test
  key.test: test_config_map_value
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: skf-flask-back
data:
  JWT_SECRET: #mash the keyboard
  SKF_API_URL: #your uri to API e.g. https://skf.example.com/api
  SKF_FLASK_DEBUG: "False"
  SKF_DB_URL: sqlite:///db/db.sqlite
  SKF_DOJO_API_KEY: optional
  SKF_DOJO_API_KEY: optional
  SKF_TESTING: "False"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: skf-flask-front
data:
  FRONTEND_URI: #your uri e.g. https://skf.example.com
